### ISSUE TITLE
COVID example configuration

### ISSUE THREAD

**Issue by ymnliu** [OHNLP/Backbone#1]
Can we have an example configuration file provided for a pre-defined user scenario?

**Comment by qqndrew** [comment]
We do already, please see

https://github.com/OHNLP/Backbone/blob/master/Example-Backbone-Configs/src/main/resources/%5Brun_nlp%5D_%5Bohdsi_cdm%5D_%5Bohdsi_cdm%5D.json

unless you mean something else?

**Comment by ymnliu** [comment]
That should be doing mostly it. Is is possible to ship a working example as well, maybe from a few test documents?

**Comment by qqndrew** [comment]
Not really - reason why is the pipeline we have set up is assuming you are reading from an OMOP CDM database you have already populated using the other example config, which uses Epic Clarity as a data faucet.

Would have to write a local file system data faucet to supply a shippeable example - which would naturally break gcp/spark support because they can't read from local file systems.... (will revisit this tomorrow)

As far as downloadable packages go, all the binary executables are already packaged in the appropriate structure and is downloadable from releases.
